Don't raise an error from Client.AddToUserAgent
Azure/go-autorest pull request #662
Opened 2021-11-15 11:44 UTC by aaron-trout

This is essentially just string concatenation, there is no real reason
to return an error here. This causes clients to write dozens of lines
of pointless error handling or just not handle the err.

Thinking about the contract of this function, if I've asked for it to
append "" (empty string) to the user agent, and it does nothing, then
it has been a success. Raising an error in that case is a bit weird.

`"foo" + ""` does not result in an error, which is essentially what
this is doing.

---

Thank you for your contribution to Go-AutoRest! We will triage and review it as soon as we can.

As part of submitting, please make sure you can make the following assertions:
 - [x] I've tested my changes, adding unit tests if applicable.
 - [x] ~I've added Apache 2.0 Headers to the top of any new source files.~ Not applicable

2021-11-16 19:00 UTC, jhendrixMSFT requested changes
While I agree that the error is useless, this would be a breaking change and the public surface area at this point is frozen.  If you want to update the doc comment explaining that this error can be ignored that would be acceptable.

2021-11-16 19:11 UTC, aaron-trout commented
@jhendrixMSFT thanks for the reply. Do you have any versioning strategy for this repo which could accommodate this change? i.e. could this be earmarked for a future "v2.0" release (or rather, v1 looking at the current version numbers).

In the mean time I will go ahead and update the docs regarding the error.

2021-11-16 20:33 UTC, aaron-trout commented
Oh interesting, so we should be updating our code to move to that new set of SDK packages I guess. Thanks for the info!

2022-04-15 18:58 UTC, jhendrixMSFT commented
Closing as stale.  Please reopen if still needed.

2022-04-15 18:58 UTC, closed without merging